# Part 1

In [35]:
# Load the input file
with open('input.txt') as f:
    input_data = f.read().splitlines()

print(input_data)

#input_data = [
#     "..@@.@@@@.",
#     "@@@.@.@.@@",
#     "@@@@@.@.@@",
#     "@.@@@@..@.",
#     "@@.@@@@.@@",
#     ".@@@@@@@.@",
#     ".@.@.@.@@@",
#     "@.@@@.@@@@",
#     ".@@@@@@@@.",
#     "@.@.@@@.@."
# ]

['.@..@@@@@.@.@@@..@.@@..@@@.@.@.....@@.@@.@@@@@@..@@@.@.@.@..@..@@@@@@@..@@@.@.@@.@@@@@@.@@@@@@@.@@@.@@@@@.@...@@@@@.@@.@...@.@@.@@.@@@@@', '@@@.@@.@@@...@.@.@..@.@@...@@@@@@@@@.@@@@@.@@@@.@@@.@@@.@..@@@@..@...@@@@..@.@@..@.@@.@@@@@@..@@@.@@.@@@@@.@....@@@@@@...@.@@@.@@....@@@', '..@@@@.@.@@@@.@@@@@...@@@.@@...@@@@...@@.@@@@.@@@@@@@@@@@.@.@@@@@@@...@@@@@.@@.@@@@.@....@@@@@@.@@@.@@@@@@@.@...@@@...@@@.@..@@@@.@@@@.@', '@@@@@@@.@.@@..@@.@@@@@@.@@@..@@@@.@@..@@@@@@@@@.@@@@@@....@..@.@@.@@.@@@@.@@@.@.@.@@@@@.@@@@..@..@@.@..@@@..@@.@@.@..@.@.@@@.@@@.@....@@', '@.@@..@.@@.@@@@..@@@@@@@@.@@@@@@@@@@@@@....@@.@@@@@@.@@@@..@.@..@@@.@@@@..@.@@@.@@.@@@@@@.@@.@@@@@@.@@.@@@@.@.@@@@@.@@@.@@@.@@@@..@@@@@@', '@@@@@.@...@.@..@@.@@..@..@@@.@.@.@.@@.@@@@.@@..@...@@@@@@@@@@@..@@@@..@@.@@..@@@@..@@@@@@@@.@@.@@@@@@@@@.@@...@...@@@..@@@@..@.@@@.@@@@.', '@@@@@@.@@@@@@@......@.@@@@@@@@@@@@.@@@@...@@@.@.@@@@@...@@.@@@@@.@@@.@@@.@@@@...@.@@@@@@@@.@.@@@..@@.@@.@@@..@@@..@@@@.@@@.@@.@@@..@..@@', '@@.@@.@@.@.@.@@@@.

In [36]:
binary_data = []
for row in input_data:
    row = row.replace('.', '0').replace('@', '1')
    binary_data.append(row)

print(binary_data)

['0100111110101110010110011101010000011011011111100111010101001001111111001110101101111110111111101110111110100011111011010001011011011111', '1110110111000101010010110001111111110111110111101110111010011110010001111001011001011011111100111011011111010000111111000101110110000111', '0011110101111011111000111011000111100011011110111111111110101111111000111110110111101000011111101110111111101000111000111010011110111101', '1111111010110011011111101110011110110011111111101111110000100101101101111011101010111110111100100110100111001101101001010111011101000011', '1011001011011110011111111011111111111110000110111111011110010100111011110010111011011111101101111110110111101011111011101110111100111111', '1111101000101001101100100111010101011011110110010001111111111100111100110110011110011111111011011111111101100010001110011110010111011110', '1111110111111100000010111111111111011110001110101111100011011111011101110111100010111111110101110011011011100111001111011101101110010011', '110110110101011110

In [37]:
# print a table to get a better visual
binary_data_table = ""
for row in binary_data:
    binary_data_table += "\t".join(row) + "\n"

print(binary_data_table)    

0	1	0	0	1	1	1	1	1	0	1	0	1	1	1	0	0	1	0	1	1	0	0	1	1	1	0	1	0	1	0	0	0	0	0	1	1	0	1	1	0	1	1	1	1	1	1	0	0	1	1	1	0	1	0	1	0	1	0	0	1	0	0	1	1	1	1	1	1	1	0	0	1	1	1	0	1	0	1	1	0	1	1	1	1	1	1	0	1	1	1	1	1	1	1	0	1	1	1	0	1	1	1	1	1	0	1	0	0	0	1	1	1	1	1	0	1	1	0	1	0	0	0	1	0	1	1	0	1	1	0	1	1	1	1	1
1	1	1	0	1	1	0	1	1	1	0	0	0	1	0	1	0	1	0	0	1	0	1	1	0	0	0	1	1	1	1	1	1	1	1	1	0	1	1	1	1	1	0	1	1	1	1	0	1	1	1	0	1	1	1	0	1	0	0	1	1	1	1	0	0	1	0	0	0	1	1	1	1	0	0	1	0	1	1	0	0	1	0	1	1	0	1	1	1	1	1	1	0	0	1	1	1	0	1	1	0	1	1	1	1	1	0	1	0	0	0	0	1	1	1	1	1	1	0	0	0	1	0	1	1	1	0	1	1	0	0	0	0	1	1	1
0	0	1	1	1	1	0	1	0	1	1	1	1	0	1	1	1	1	1	0	0	0	1	1	1	0	1	1	0	0	0	1	1	1	1	0	0	0	1	1	0	1	1	1	1	0	1	1	1	1	1	1	1	1	1	1	1	0	1	0	1	1	1	1	1	1	1	0	0	0	1	1	1	1	1	0	1	1	0	1	1	1	1	0	1	0	0	0	0	1	1	1	1	1	1	0	1	1	1	0	1	1	1	1	1	1	1	0	1	0	0	0	1	1	1	0	0	0	1	1	1	0	1	0	0	1	1	1	1	0	1	1	1	1	0	1
1	1	1	1	1	1	1	0	1	0	1	1	0	0	1	1	0	1	1	1	1	1	1	0	1	1	1	0	0	1	1	1	1	0	1	1	0	0	1	1	1	1	1	1	1	1	1	0	1	1	1	1	1	1	0	0	0	0	1	0	0	1	0	1	1	0	1	1	0	1	1	1	1	0	1	1	1	0	1	0	1	0	1	1	1	1	1	0	1	1	1	1	

In [38]:
# create a map object with numpy
import numpy as np
map_array = np.array([list(row) for row in binary_data], dtype=int)
print(map_array)

[[0 1 0 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 1 ... 1 0 1]
 ...
 [1 1 0 ... 1 0 1]
 [0 0 1 ... 0 0 0]
 [1 1 1 ... 0 1 1]]


In [39]:
# get the positions of each field with a value of 1
positions = np.argwhere(map_array == 1)
print(positions)

[[  0   1]
 [  0   4]
 [  0   5]
 ...
 [135 132]
 [135 134]
 [135 135]]


In [40]:
def get_neighbors(pos, map_array):
    neighbors = []
    x, y = pos
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1), (-1, -1), (-1, 1), (1, -1), (1, 1)] # 8 directions
    for dx, dy in directions:
        nx, ny = x + dx, y + dy
        # get the value of the neighbor if it's within bounds
        if 0 <= nx < map_array.shape[0] and 0 <= ny < map_array.shape[1]:
            neighbors.append((int(map_array[nx, ny])))
    return neighbors

accessible_rolls = 0
for pos in positions:
    neighbors = get_neighbors(pos, map_array)
    if sum(neighbors) < 4:
        accessible_rolls += 1

print("Number of reachable paper:", accessible_rolls)

Number of reachable paper: 1464


# Part 2

In [41]:
accessible_rolls = 0
map_array_copy = np.zeros_like(map_array)

while not np.array_equal(map_array, map_array_copy):
    map_array_copy = map_array.copy()
    for pos in positions:
        neighbors = get_neighbors(pos, map_array)
        if sum(neighbors) < 4:
            map_array[pos[0], pos[1]] = 0
            accessible_rolls += 1
            positions = np.argwhere(map_array == 1)
    
print("Number of reachable paper:", accessible_rolls)

Number of reachable paper: 8409
